### ISSUE TITLE
1.1.0 release errors on local path actions, when 1.0.4 did not

### ISSUE THREAD

**Issue by nackerman-nydig** [zgosalvez/github-actions-ensure-sha-pinned-actions#10]
there appears to be a regression since the last release. Now, this action is erroring on local actions. for example:

v 1.0.4 -> Correctly doesnt error for local actions
```
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@8877889a5717dad0b139f1d2925689aa68f88a43
```
however, v1.1.0 -> Will error on my local action -> ```Error: ./.github/actions/prepare is not pinned to a full length commit SHA.```

```
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@7692976b7529253c9610ff3242b2693d678847b0
```

Seems likely some unintended behavior was added in @xunleii recent merge

**Comment by xunleii** [comment]
Oh, really sorry, I didn't check this case when I made the #7

**Comment by nackerman-nydig** [comment]
No Worries! Thanks for jumping on the fix :)

**Comment by zgosalvez** [comment]
@nackerman-nydig, please check #12 before I create a new release.
