### ISSUE TITLE
Issues with shared Github Actions workflows

### ISSUE THREAD

**Issue by xunleii** [zgosalvez/github-actions-ensure-sha-pinned-actions#4]
Hi @zgosalvez 

Firstly, thanks a lot for this Action, I use it every day.

I'm currently [sharing my day-to-day workflows](https://github.blog/changelog/2021-10-05-github-actions-dry-your-github-actions-configuration-by-reusing-workflows/) on a [this repository](https://github.com/xunleii/github-actions-grimoire) and your Action currently fails with the new syntax (see https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#calling-a-reusable-workflow) (if you need more information, [here is](https://github.com/xunleii/github-actions-grimoire/actions/runs/1313842455) the failed job). 
Furthermore, I think we can ensure that theses shared workflow should be pinned like other `uses` fields.

**Comment by zgosalvez** [comment]
Finally, GitHub allows for reusing workflows. This is very new, and I'll need time to learn the changes and review the code to support the new syntax. Hopefully, we can have version 2 released soon, but any PR is welcome!

**Comment by xunleii** [comment]
@zgosalvez I made a PR to add compatibility with this new Github feature
