### ISSUE TITLE
Allow whitelisting certain actions

### ISSUE THREAD

**Issue by nackerman-nydig** [zgosalvez/github-actions-ensure-sha-pinned-actions#6]
Thanks for making this! Great use case. 

We'd like the ability to "trust" certain actions. For example: ```actions/checkout@v2.3.4``` is maintained by github, a group I trust to not inject malicous code out of the blue.

Other actions we arent so trusting of, and would like to see a failed workflow for non-sha-pins (The existing behavior).

PR -> https://github.com/zgosalvez/github-actions-ensure-sha-pinned-actions/pull/5

**Comment by sshine** [comment]
The PR is now at #9, awaiting review.

**Comment by kuhnroyal** [comment]
Could really use this for GHE reusable workflows.

**Comment by zgosalvez** [comment]
#16
